//go:build linux

package prototype

import (
	"bytes"
	"errors"
	"net/netip"
	"sync"
	"testing"
	"time"

	"github.com/noranite/Noranite-l3/internal/dataplane"
	"github.com/noranite/Noranite-l3/internal/server"
)

func TestServerEngineDrainOrderAllowsRXGeneratedACKThroughTX(t *testing.T) {
	var routeKey, c2s, s2c [32]byte
	for i := 0; i < 32; i++ {
		routeKey[i] = byte(i + 1)
		c2s[i] = byte(0x40 + i)
		s2c[i] = byte(0x80 + i)
	}

	const sessionID uint64 = 0x91b3
	serverSession, err := dataplane.NewSession(sessionID, s2c, c2s, 0)
	if err != nil {
		t.Fatalf("NewSession(server): %v", err)
	}
	clientSession, err := dataplane.NewSession(sessionID, c2s, s2c, 0)
	if err != nil {
		t.Fatalf("NewSession(client): %v", err)
	}

	peerIP := netip.MustParseAddr("10.66.0.2")
	core, err := server.New(server.Config{
		RouteKey:           routeKey,
		MaxInnerPacketSize: 1380,
		Lifecycle: server.LifecycleConfig{
			GenerationLifetime: 30 * time.Second,
			ReceiveGrace:       5 * time.Second,
		},
		Peers: []server.PeerConfig{{TunnelIPv4: peerIP}},
	})
	if err != nil {
		t.Fatalf("server.New: %v", err)
	}
	if err := core.InstallPendingSession(peerIP, serverSession); err != nil {
		t.Fatalf("InstallPendingSession: %v", err)
	}

	var sentMu sync.Mutex
	var sent []server.TXPacket
	errC := make(chan error, 4)
	reporter := runtimeErrorReporter{c: errC}

	txEngine, err := server.NewOwnedTXEngine(
		core,
		server.TXEngineConfig{EncryptWorkers: 2, BatchSize: 2},
		func(packets []server.TXPacket) error {
			sentMu.Lock()
			defer sentMu.Unlock()
			for _, packet := range packets {
				sent = append(sent, server.TXPacket{
					Wire:        bytes.Clone(packet.Wire),
					Destination: packet.Destination,
				})
			}
			return nil
		},
		reporter.Report,
	)
	if err != nil {
		t.Fatalf("NewOwnedTXEngine: %v", err)
	}

	wireBufferSize := 1380 + dataplane.MaxDataExpansion
	if wireBufferSize < dataplane.MaxGeneratedEstablishmentWirePacketSize {
		wireBufferSize = dataplane.MaxGeneratedEstablishmentWirePacketSize
	}
	rxPool := newRuntimePacketPool(wireBufferSize, 2)
	controlPool := newRuntimePacketPool(wireBufferSize, 2)

	rxEngine, err := server.NewOwnedRXEngine(
		core,
		server.RXEngineConfig{DecryptWorkers: 2, BatchSize: 2},
		newServerRXConsumer(nil, txEngine, controlPool, 2),
		reporter.Report,
	)
	if err != nil {
		txEngine.Close()
		t.Fatalf("NewOwnedRXEngine: %v", err)
	}

	clientScratch, err := dataplane.NewDataScratch(routeKey)
	if err != nil {
		t.Fatalf("NewDataScratch(client): %v", err)
	}
	const keepaliveID uint64 = 0x0123456789abcdef
	keepaliveStorage := make([]byte, 0, dataplane.MaxGeneratedControlWirePacketSize)
	keepalive, _, err := clientSession.SealKeepaliveToWithPadding(
		clientScratch,
		keepaliveStorage,
		keepaliveID,
		dataplane.MinGeneratedControlWirePacketSize-dataplane.MinControlWirePacketSize+8,
	)
	if err != nil {
		t.Fatalf("SealKeepaliveToWithPadding: %v", err)
	}

	rxBuffer := rxPool.Get()
	copy(rxBuffer, keepalive)
	packet := rxBuffer[:len(keepalive)]
	source := netip.MustParseAddrPort("192.0.2.123:52123")
	admitScratch, err := core.NewDataScratch()
	if err != nil {
		t.Fatalf("core.NewDataScratch: %v", err)
	}
	op, err := core.AdmitNetworkDatagram(admitScratch, source, packet)
	if err != nil {
		t.Fatalf("AdmitNetworkDatagram(KEEPALIVE): %v", err)
	}
	if err := rxEngine.EnqueueOwnedBatch(
		[]server.RXOwnedSubmission{{Operation: *op}},
		true,
		rxPool,
	); err != nil {
		t.Fatalf("RX EnqueueOwnedBatch(KEEPALIVE): %v", err)
	}

	// This is the production drain order: RX first while TX remains open for ACK
	// submissions generated by accepted receive operations, then TX.
	rxEngine.Close()
	txEngine.Close()

	select {
	case runtimeErr := <-errC:
		t.Fatalf("runtime drain error: %v", runtimeErr)
	default:
	}

	if core.CurrentSession(peerIP) != serverSession {
		t.Fatal("accepted pending KEEPALIVE was not promoted during RX drain")
	}

	sentMu.Lock()
	defer sentMu.Unlock()
	if len(sent) != 1 {
		t.Fatalf("sent packets=%d, want exactly one drained ACK", len(sent))
	}
	if sent[0].Destination != source {
		t.Fatalf("ACK destination=%v, want %v", sent[0].Destination, source)
	}
	if len(sent[0].Wire) > len(keepalive) {
		t.Fatalf("ACK wire size=%d exceeds triggering KEEPALIVE size=%d", len(sent[0].Wire), len(keepalive))
	}

	ackScratch, err := dataplane.NewDataScratch(routeKey)
	if err != nil {
		t.Fatalf("NewDataScratch(ACK): %v", err)
	}
	route, err := dataplane.DecodeRoute(ackScratch, sent[0].Wire)
	if err != nil {
		t.Fatalf("DecodeRoute(ACK): %v", err)
	}
	if route.SessionID != sessionID {
		t.Fatalf("ACK session=%#x, want %#x", route.SessionID, sessionID)
	}
	plaintext, err := clientSession.AuthenticateInPlace(
		ackScratch,
		sent[0].Wire,
		route.Sequence,
	)
	if err != nil {
		t.Fatalf("AuthenticateInPlace(ACK): %v", err)
	}
	control, err := dataplane.ParseControl(plaintext)
	if err != nil {
		t.Fatalf("ParseControl(ACK): %v", err)
	}
	if control.Type != dataplane.ControlACK || control.KeepaliveID != keepaliveID {
		t.Fatalf("ACK control=%+v, want keepalive_id %#x", control, keepaliveID)
	}
}

func TestServerRXConsumerTreatsACKSequenceExhaustionAsTerminal(t *testing.T) {
	pool := newRuntimePacketPool(64, 1)
	consumer := newServerRXConsumer(nil, nil, pool, 1)

	err := consumer([]server.RXOwnedResult{{Err: dataplane.ErrSequenceExhausted}})
	if !errors.Is(err, dataplane.ErrSequenceExhausted) {
		t.Fatalf("consumer error=%v, want ErrSequenceExhausted", err)
	}
}

func TestServerRXConsumerFlushesPartialACKBatchBeforeBlockingOnControlPool(t *testing.T) {
	var routeKey, c2s, s2c [32]byte
	for i := 0; i < 32; i++ {
		routeKey[i] = byte(i + 1)
		c2s[i] = byte(0x40 + i)
		s2c[i] = byte(0x80 + i)
	}

	const sessionID uint64 = 0x91c4
	serverSession, err := dataplane.NewSession(sessionID, s2c, c2s, 0)
	if err != nil {
		t.Fatalf("NewSession(server): %v", err)
	}
	peerIP := netip.MustParseAddr("10.66.0.2")
	core, err := server.New(server.Config{
		RouteKey:           routeKey,
		MaxInnerPacketSize: 1380,
		Lifecycle: server.LifecycleConfig{
			GenerationLifetime: 30 * time.Second,
			ReceiveGrace:       5 * time.Second,
		},
		Peers: []server.PeerConfig{{TunnelIPv4: peerIP, InitialSession: serverSession}},
	})
	if err != nil {
		t.Fatalf("server.New: %v", err)
	}

	endpoint := netip.MustParseAddrPort("192.0.2.210:52210")
	if _, err := serverSession.CommitAuthenticatedRX(0, endpoint); err != nil {
		t.Fatalf("CommitAuthenticatedRX(endpoint): %v", err)
	}

	makeOutbound := func(marker byte) server.OutboundOperation {
		t.Helper()
		inner := clientRuntimeIPv4Packet(
			t,
			netip.MustParseAddr("10.66.0.1"),
			peerIP,
			[]byte{marker},
		)
		var op server.OutboundOperation
		if err := core.AdmitInnerPacketInto(&op, inner, 2048); err != nil {
			t.Fatalf("AdmitInnerPacketInto(%d): %v", marker, err)
		}
		return op
	}
	op1 := makeOutbound(1)
	op2 := makeOutbound(2)

	errC := make(chan error, 4)
	reporter := runtimeErrorReporter{c: errC}
	var sentMu sync.Mutex
	sent := 0
	txEngine, err := server.NewOwnedTXEngine(
		core,
		server.TXEngineConfig{
			EncryptWorkers:   1,
			EncryptQueueSize: 1,
			PeerQueueSize:    1,
			BatchSize:        2,
		},
		func(packets []server.TXPacket) error {
			sentMu.Lock()
			sent += len(packets)
			sentMu.Unlock()
			return nil
		},
		reporter.Report,
	)
	if err != nil {
		t.Fatalf("NewOwnedTXEngine: %v", err)
	}

	// One buffer is intentionally smaller than the two-result consumer batch.
	// The consumer must enqueue its partial ACK vector before blocking for the
	// second buffer, otherwise no TX work exists that could return the first one.
	controlPool := newRuntimePacketPool(2048, 1)
	consumer := newServerRXConsumer(nil, txEngine, controlPool, 2)
	done := make(chan error, 1)
	go func() {
		done <- consumer([]server.RXOwnedResult{
			{Inbound: dataplane.InboundPacket{Kind: dataplane.InboundKeepalive}, Outbound: op1, HasOutbound: true},
			{Inbound: dataplane.InboundPacket{Kind: dataplane.InboundKeepalive}, Outbound: op2, HasOutbound: true},
		})
	}()

	select {
	case err := <-done:
		if err != nil {
			t.Fatalf("RX consumer: %v", err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("RX consumer blocked with a partial ACK batch and exhausted control pool")
	}

	txEngine.Close()
	select {
	case runtimeErr := <-errC:
		t.Fatalf("runtime error: %v", runtimeErr)
	default:
	}

	sentMu.Lock()
	gotSent := sent
	sentMu.Unlock()
	if gotSent != 2 {
		t.Fatalf("sent packets=%d, want 2", gotSent)
	}
	buffer, ok := controlPool.TryGet()
	if !ok {
		t.Fatal("control pool buffer was not returned after TX drain")
	}
	controlPool.Put(buffer)
}
